'use strict';
const { DatabaseSync } = require('node:sqlite');
const VERSION = 1, MAGIC = 0x53514c31, MAX_FRAME = 8 * 1024 * 1024;
let db = null, expected = 1, input = Buffer.alloc(0), cursor = null;

const crcTable = (() => { const t = new Uint32Array(256); for (let n=0;n<256;n++){let c=n;for(let k=0;k<8;k++)c=(c&1)?0xedb88320^(c>>>1):c>>>1;t[n]=c>>>0;} return t; })();
function crc32(b){let c=0xffffffff;for(const x of b)c=crcTable[(c^x)&255]^(c>>>8);return (c^0xffffffff)>>>0;}
function frame(value){const body=Buffer.from(JSON.stringify(value),'utf8');if(body.length>MAX_FRAME)throw new Error('frame too large');const h=Buffer.alloc(14);h.writeUInt32BE(MAGIC,0);h.writeUInt16BE(VERSION,4);h.writeUInt32BE(body.length,6);h.writeUInt32BE(crc32(body),10);return Buffer.concat([h,body]);}
function send(value){if(!process.stdout.write(frame(value)))process.stdin.pause();}
process.stdout.on('drain',()=>process.stdin.resume());
function consume(chunk,onValue){input=Buffer.concat([input,chunk]);for(;;){if(input.length<14)return;if(input.readUInt32BE(0)!==MAGIC||input.readUInt16BE(4)!==VERSION)throw new Error('bad frame header');const n=input.readUInt32BE(6);if(n>MAX_FRAME)throw new Error('oversize frame');if(input.length<14+n)return;const body=input.subarray(14,14+n);if(crc32(body)!==input.readUInt32BE(10))throw new Error('bad frame crc');input=input.subarray(14+n);onValue(JSON.parse(body.toString('utf8')));}}
function sqliteKind(error){const n=Number(error&&error.errcode);if(n===5)return'busy';if(n===6)return'locked';if(n===8)return'read-only';if(n===11)return'corrupt';if(n===17)return'schema-changed';if(n>=19&&n<20)return'constraint';if(n===18)return'limit-exceeded';return'invalid-sql';}
function fail(id,error,entered){send({v:VERSION,id,kind:'error',entered,errorKind:sqliteKind(error),errorCode:Number(error&&error.errcode)||0,errorMessage:String(error&&error.message||'SQLite operation failed').slice(0,512)});}
function assertAuto(inTx){if(!!db.isTransaction!==inTx)throw Object.assign(new Error('autocommit invariant violated'),{errcode:21});}
function decode(v){switch(v.t){case'null':return null;case'integer':return BigInt(v.v);case'real':if(!Number.isFinite(v.v))throw new TypeError('non-finite REAL');return v.v;case'text':return v.v;case'blob':return Uint8Array.from(v.v);default:throw new TypeError('invalid binding');}}
function encode(v){if(v===null)return{t:'null'};if(typeof v==='bigint')return{t:'integer',v:String(v)};if(typeof v==='number')return{t:'real',v};if(typeof v==='string')return{t:'text',v};if(v instanceof Uint8Array)return{t:'blob',v:Array.from(v)};throw new TypeError('unsupported SQLite value');}
function significantTail(sql){let q=null,line=false,block=false,semi=-1;for(let i=0;i<sql.length;i++){const c=sql[i],n=sql[i+1];if(line){if(c==='\n'||c==='\r')line=false;continue;}if(block){if(c==='*'&&n==='/'){block=false;i++;}continue;}if(q){if(c===q){if(n===q)i++;else q=null;}continue;}if(c==="'"||c==='"'||c==='`'){q=c;continue;}if(c==='['){q=']';continue;}if(c==='-'&&n==='-'){line=true;i++;continue;}if(c==='/'&&n==='*'){block=true;i++;continue;}if(c===';'){semi=i;break;}}if(semi<0)return false;return sql.slice(semi+1).replace(/--[^\r\n]*(?:\r?\n|$)|\/\*[\s\S]*?\*\//g,'').trim().length>0;}
function statement(req){if(significantTail(req.sql))throw Object.assign(new Error('significant SQL tail'),{errcode:1});const stmt=db.prepare(req.sql);return{stmt,args:req.bindings.map(decode)};}
function closeCursor(){if(!cursor)return;const c=cursor;cursor=null;try{c.iterator.return();}finally{assertAuto(c.inTx);}}
function demand(req){if(!cursor||req.id!==cursor.id)throw new Error('unexpected row demand');const c=cursor;assertAuto(c.inTx);const item=c.iterator.next();assertAuto(c.inTx);if(item.done){cursor=null;send({v:VERSION,id:c.id,kind:'done'});return;}const row=item.value.map(encode),bytes=Buffer.byteLength(JSON.stringify(row));c.rows++;c.bytes+=bytes;if(c.rows>c.rowLimit||c.bytes>c.byteLimit){closeCursor();throw Object.assign(new Error('collection limit exceeded'),{errcode:18});}send({v:VERSION,id:c.id,kind:'row',row});}
function open(req){if(db)return;const c=req.options;db=new DatabaseSync(c.path,{readOnly:c.readOnly,timeout:c.busyTimeout,readBigInts:true,returnArrays:true});db.exec('PRAGMA foreign_keys=ON');if(!c.readOnly)db.exec('PRAGMA journal_mode=WAL');db.exec('PRAGMA synchronous=FULL');db.exec('PRAGMA temp_store=MEMORY');assertAuto(false);}
function handle(req){if(req.v!==VERSION||!Number.isSafeInteger(req.id)||req.id<1)throw new Error('protocol identity');if(req.op==='demand'){try{demand(req);}catch(e){const id=cursor?cursor.id:req.id;try{closeCursor();}catch(_){}fail(id,e,true);}return;}if(cursor)throw new Error('request while cursor active');if(req.id!==expected++)throw new Error('protocol sequence');let entered=false;try{if(req.op==='open'){open(req);send({v:VERSION,id:req.id,kind:'done'});return;}if(!db)throw new Error('not open');const inTx=req.inTransaction===true;assertAuto(inTx);if(req.op==='execute'){const{stmt,args}=statement(req);entered=true;const r=stmt.run(...args);assertAuto(inTx);send({v:VERSION,id:req.id,kind:'done',changedRows:Number(r.changes),lastInsertRowId:String(r.lastInsertRowid)});return;}if(req.op==='query'){const{stmt,args}=statement(req);entered=true;const iterator=stmt.iterate(...args);assertAuto(inTx);cursor={id:req.id,iterator,inTx,rowLimit:req.rowLimit,byteLimit:req.byteLimit,rows:0,bytes:0};send({v:VERSION,id:req.id,kind:'columns',columns:stmt.columns().map(c=>c.name)});return;}if(req.op==='begin'){db.exec('BEGIN '+req.mode);assertAuto(true);send({v:VERSION,id:req.id,kind:'done'});return;}if(req.op==='commit'){entered=true;db.exec('COMMIT');assertAuto(false);send({v:VERSION,id:req.id,kind:'done'});return;}if(req.op==='rollback'){db.exec('ROLLBACK');assertAuto(false);send({v:VERSION,id:req.id,kind:'done'});return;}throw new Error('unknown operation');}catch(e){try{closeCursor();}catch(_){}fail(req.id,e,entered);}}
process.stdin.on('data',chunk=>{try{consume(chunk,handle);}catch(e){process.exitCode=71;process.stdin.destroy();}});
process.stdin.on('end',()=>{try{closeCursor();}catch(_){}try{if(db&&db.isTransaction)db.exec('ROLLBACK');}catch(_){}try{if(db)db.close();}catch(_){}process.exit(0);});
send({v:VERSION,id:0,kind:'ready',creditMessages:1,creditBytes:MAX_FRAME});
module.exports={frame,crc32};
