"use strict";
const fs=require("node:fs"),path=require("node:path"),vm=require("node:vm"),{fork}=require("node:child_process"),{DatabaseSync}=require("node:sqlite");
const root=path.resolve(__dirname,"..");
function load(file,flags){const source=fs.readFileSync(file,"utf8");const context={console,process,require,setTimeout,clearTimeout,Buffer,URL};vm.createContext(context);vm.runInContext(source,context,{filename:file});return new Promise((resolve,reject)=>{const app=context.Elm.Main.init({flags});const timer=setTimeout(()=>reject(new Error("fixture timeout")),5000);app.ports.report.subscribe(raw=>{clearTimeout(timer);resolve(JSON.parse(raw));});});}
async function interrupt(file,dbPath){try{fs.unlinkSync(dbPath);}catch(_){}
 const child=fork(path.join(root,"feasibility/child.cjs"),[file,dbPath],{stdio:["ignore","ignore","inherit","ipc"]});let started=false;child.on("message",m=>{if(m&&m.type==="started")started=true;});const began=Date.now();let ticks=0;const tick=setInterval(()=>ticks++,5);await new Promise(r=>setTimeout(r,150));child.kill("SIGKILL");const exit=await new Promise(resolve=>child.once("exit",(code,signal)=>resolve({code,signal})));clearInterval(tick);const db=new DatabaseSync(dbPath,{readBigInts:true,returnArrays:true});const count=db.prepare("SELECT count(*) FROM interruption_probe").get()[0];db.close();return {started,exit,ticks,elapsedMs:Date.now()-began,rollbackAfterKill:String(count)==="0"};}

(async()=>{for(const mode of ["debug","optimize"]){const file=path.join(root,`build/feasibility-${mode}.js`),basic=await load(file,{mode:"basic",path:path.join(root,`build/basic-${mode}.sqlite3`)}),interruption=await interrupt(file,path.join(root,`build/interrupt-${mode}.sqlite3`));console.log(JSON.stringify({mode,basic,interruption},null,2));if(!basic.ok||ticksBad(interruption))process.exitCode=1;}})().catch(e=>{console.error(e);process.exit(1);});
function ticksBad(x){return !x.started||x.ticks<5||!x.rollbackAfterKill||x.exit.signal!=="SIGKILL";}
